#cloud-config

write_files:
- path: /tmp/enable_maintenance_mode.sh
  permissions: '0755'
  content: | 
    #!/bin/bash
    echo 'test'
- path: /tmp/disable_maintenance_mode.sh
  permissions: '0755'
  content: | 
    #!/bin/bash
    echo 'test'