FROM composer:latest as composer

FROM google/cloud-sdk:slim as base
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN apt-get update && apt-get install -y unzip
RUN mkdir /opt/src/
WORKDIR /opt/src/
COPY ./* ./
RUN chmod 777 download_secrets.sh
CMD /opt/src/download_secrets.sh