name: Terraform Lint
on:
  pull_request:
    branches: [main, stage]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.44.1

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact