name: Terraform Lint
on:
  pull_request:
    branches: [main, stage]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: latest

    - uses: terraform-linters/tflint-load-config-action@v1
      name: Configure TFLint
      with:
        source-repo: me/tflint-config

    - name: Initialize TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact